### ISSUE TITLE
while communicating with PODM with PSME ,PSME is discovered and througing EJBTransactionRolledbackException

### ISSUE THREAD

**Issue by lalithabheemavarapu** [intel/intelRSD#106]
After PODM succesful service running,while communicating with PODM with PSME,PSME is discovered througing EJBTransactionRolledbackException.Attached podm-manager-application-Log.
In our requirement currently we are using SSDP protocol.
[pod-manager-application.log](https://github.com/intel/intelRSD/files/3155157/pod-manager-application.log)
2019-05-06 19:47:33,245 [ServerService Thread Pool -- 66] DEBUG c.i.podm.discovery.DiscoveryStartup - Sanitizing existing external services
2019-05-06 19:47:33,269 [ServerService Thread Pool -- 73] DEBUG c.i.p.b.r.s.b.DeepDiscoveryStartup - Reinitializing deep discovery process on computer systems that were left in DeepInProgress state
2019-05-06 19:47:33,287 [ServerService Thread Pool -- 65] DEBUG c.i.p.d.e.ServiceRemovalTaskScheduler - Scheduling Service Removal Task...
2019-05-06 19:47:33,288 [ServerService Thread Pool -- 68] DEBUG c.i.p.b.r.s.a.AllocationStartup - Failing all composed nodes that were not assembled before restart
2019-05-06 19:47:33,322 [ServerService Thread Pool -- 66] INFO  c.i.p.s.d.ssdp.SsdpServiceDetector - Initializing SSDP based service detector...
2019-05-06 19:47:33,409 [ServerService Thread Pool -- 66] INFO  com.intel.podm.ApplicationStartup - PodM started (version: 0.99)
2019-05-07 00:08:35,357 [EE-ManagedExecutorService-SSDPExecutor-Thread-17] DEBUG c.i.p.s.d.ssdp.SsdpRegistryObserver - SSDP resource detected: (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:e8681296-7096-11e9-9232-7739b76c3bc1, Descriptor: http://192.168.1.53:8443/redfish/v1, Root: true
2019-05-07 00:08:35,408 [EE-ManagedExecutorService-SSDPExecutor-Thread-17] INFO  c.i.p.c.s.SerialExecutorRegistry - Creating serial executorService for e8681296-7096-11e9-9232-7739b76c3bc1
2019-05-07 00:08:35,425 [EE-ManagedExecutorService-SSDPExecutor-Thread-17] INFO  c.i.p.c.s.SerialExecutorImpl - $$$step 1-4
2019-05-07 00:08:35,425 [EE-ManagedExecutorService-SSDPExecutor-Thread-17] INFO  c.i.p.c.s.SerialExecutorImpl - $$$step 1-4
2019-05-07 00:08:35,427 [EE-ManagedScheduledExecutorService-TasksExecutor-Thread-1] DEBUG c.i.p.c.s.SerialExecutorImpl - Coordinated Task (async) com.intel.podm.discovery.external.ServiceDetectionListenerImpl$$Lambda$1009/1322818801@385a0433/e8681296-7096-11e9-9232-7739b76c3bc1 - started
2019-05-07 00:08:35,427 [EE-ManagedScheduledExecutorService-TasksExecutor-Thread-1] DEBUG c.i.p.c.s.SerialExecutorImpl - Coordinated Task (async) com.intel.podm.discovery.external.ServiceDetectionListenerImpl$$Lambda$1009/1322818801@385a0433/e8681296-7096-11e9-9232-7739b76c3bc1 - started
2019-05-07 00:08:35,427 [EE-ManagedScheduledExecutorService-TasksExecutor-Thread-1] INFO  c.i.p.d.e.ServiceDetectionListenerImpl - Service {URI=http://192.168.1.53:8443/redfish/v1, type=PSME, UUID=e8681296-7096-11e9-9232-7739b76c3bc1} detected
2019-05-07 00:08:35,456 [EE-ManagedScheduledExecutorService-TasksExecutor-Thread-1] INFO  c.i.p.d.e.ExternalServiceUpdater[ServiceLifecycle] - New service ExternalService {UUID=e8681296-7096-11e9-9232-7739b76c3bc1, baseUri=null, type=PSME} discovered.
2019-05-07 00:08:35,456 [EE-ManagedScheduledExecutorService-TasksExecutor-Thread-1] INFO  c.i.p.d.e.ExternalServiceUpdater[ServiceLifecycle] - Service's URI for ExternalService {UUID=e8681296-7096-11e9-9232-7739b76c3bc1, baseUri=null, type=PSME} was updated to http://192.168.1.53:8443/redfish/v1
2019-05-07 00:08:35,543 [EE-ManagedScheduledExecutorService-TasksExecutor-Thread-1] ERROR c.i.p.c.s.SerialExecutorImpl - Asynchronous operation (com.intel.podm.discovery.external.ServiceDetectionListenerImpl$$Lambda$1009/1322818801@385a0433) execution finished with exception
java.util.concurrent.CompletionException: javax.ejb.EJBTransactionRolledbackException: Couldn't create valid PodM Event Service destination
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[na:1.8.0_191]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[na:1.8.0_191]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629) ~[na:1.8.0_191]
	at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:235) ~[metrics-core-3.1.2.jar:3.1.2]
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledRunnable.run(ControlPointUtils.java:105) ~[wildfly-ee-12.0.0.Final.jar!/:12.0.0.Final]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_191]
	at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:141) ~[javax.enterprise.concurrent-1.0.jar!/:na]
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$101(ManagedScheduledThreadPoolExecutor.java:383) ~[javax.enterprise.concurrent-1.0.jar!/:na]
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:532) ~[javax.enterprise.concurrent-1.0.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250) ~[javax.enterprise.concurrent-1.0.jar!/:na]
	at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:78) ~[na:na]
Caused by: javax.ejb.EJBTransactionRolledbackException: Couldn't create valid PodM Event Service destination
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.handleInCallerTx(CMTTxInterceptor.java:158) ~[wildfly-ejb3-12.0.0.Final.jar!/:12.0.0.Final]
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:255) ~[wildfly-ejb3-12.0.0.Final.jar!/:12.0.0.Final]
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:332) ~[wildfly-ejb3-12.0.0.Final.jar!/:12.0.0.Final]
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:238) ~[wildfly-ejb3-12.0.0.Final.jar!/:12.0.0.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[na:na]
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509) ~[na:na]
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72) ~[weld-ejb-3.0.3.Final.jar!/:3.0.3.Final]
	at org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:89) ~[na:na]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[na:na]
	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41) ~[wildfly-ejb3-12.0.0.Final.jar!/:12.0.0.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422) ~[na:na]
	at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:47) ~[wildfly-ejb3-12.0.0.Final.jar!/:12.0.0.Final]

Can anyone please help me on this.

Thanks
Lalitha

**Comment by lalithabheemavarapu** [comment]
Closing the issue , tried some security from PODM userguide v2.3.2.
