### ISSUE TITLE
ServiceRemovalTask task finished exceptionally

### ISSUE THREAD

**Issue by rwleea** [intel/intelRSD#44]
Dear Intel,

Now I  use pod-manager 2.1.3, and I occasionally get  "ServiceRemovalTask task finished exceptionally" error. after I get this error message, I must need to restart pod-manager.

It seems ServiceRemovalTask  cannot get singleton bean "DiscoveryScheduler "'s lock. 
Do you have plan to fix the issue? 
or Can you give me some suggestions to handle this error? 

exception message:
2018-01-29 23:58:04,744 [EE-ManagedScheduledExecutorService-TasksExecutor-Thread-1] ERROR c.i.p.c.s.TaskCoordinatorImpl - Scheduled 'ServiceRemovalTask$Proxy$_$$_WeldSubclass' task finished exceptionally. Will not be scheduled again.
javax.ejb.ConcurrentAccessTimeoutException: WFLYEJB0241: EJB 3.1 PFD2 4.8.5.5.1 concurrent access timeout on DiscoveryScheduler - could not obtain lock within 5000MILLISECONDS
	at org.jboss.as.ejb3.concurrency.ContainerManagedConcurrencyInterceptor.processInvocation(ContainerManagedConcurrencyInterceptor.java:106) ~[wildfly-ejb3-10.0.0.Final.jar!/:10.0.0.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340) ~[na:na]
	at org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64) ~[wildfly-ejb3-10.0.0.Final.jar!/:10.0.0.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340) ~[na:na]
	at org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:66) ~[wildfly-ejb3-10.0.0.Final.jar!/:10.0.0.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340) ~[na:na]
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50) ~[na:na]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340) ~[na:na]
	at org.jboss.as.ejb3.component.interceptors.AdditionalSetupInterceptor.processInvocation(AdditionalSetupInterceptor.java:54) ~[wildfly-ejb3-10.0.0.Final.jar!/:10.0.0.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340) ~[na:na]
	at org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:64) ~[na:na]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340) ~[na:na]
	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:356) ~[na:na]
	at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:636) ~[na:na]
	at org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:61) ~[na:na]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340) ~[na:na]
	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:356) ~[na:na]
	at org.jboss.invocation.PrivilegedWithCombinerInterceptor.processInvocation(PrivilegedWithCombinerInterceptor.java:80) ~[na:na]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340) ~[na:na]
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61) ~[na:na]
	at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:195) ~[na:na]
	at org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:185) ~[na:na]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340) ~[na:na]
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61) ~[na:na]
	at org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:73) ~[na:na]
	at com.intel.podm.discovery.external.DiscoveryScheduler$$$view13.cancel(Unknown Source) ~[podm-discovery-2.1.3.4.0.jar:na]
	at sun.reflect.GeneratedMethodAccessor1426.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.jboss.weld.util.reflection.Reflections.invokeAndUnwrap(Reflections.java:436) ~[weld-core-impl-2.3.2.Final.jar!/:2.3.2.Final]
	at org.jboss.weld.bean.proxy.EnterpriseBeanProxyMethodHandler.invoke(EnterpriseBeanProxyMethodHandler.java:127) ~[weld-core-impl-2.3.2.Final.jar!/:2.3.2.Final]
	at org.jboss.weld.bean.proxy.EnterpriseTargetBeanInstance.invoke(EnterpriseTargetBeanInstance.java:56) ~[weld-core-impl-2.3.2.Final.jar!/:2.3.2.Final]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100) ~[weld-core-impl-2.3.2.Final.jar!/:2.3.2.Final]
	at com.intel.podm.discovery.external.DiscoveryScheduler$Proxy$_$$_Weld$EnterpriseProxy$.cancel(Unknown Source) ~[podm-discovery-2.1.3.4.0.jar:na]
	at com.intel.podm.discovery.external.ServiceRemovalTask.run(ServiceRemovalTask.java:63) ~[podm-discovery-2.1.3.4.0.jar:na]
	at com.intel.podm.discovery.external.ServiceRemovalTask$Proxy$_$$_WeldSubclass.run$$super(Unknown Source) ~[podm-discovery-2.1.3.4.0.jar:na]
	at sun.reflect.GeneratedMethodAccessor330.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:49) ~[weld-core-impl-2.3.2.Final.jar!/:2.3.2.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:77) ~[weld-core-impl-2.3.2.Final.jar!/:2.3.2.Final]
	at com.arjuna.ats.jta.cdi.transactional.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:117) ~[narayana-jts-idlj-5.2.12.Final.jar!/:5.2.12.Final (revision: f6563)]
	at com.arjuna.ats.jta.cdi.transactional.TransactionalInterceptorRequiresNew.doIntercept(TransactionalInterceptorRequiresNew.java:60) ~[narayana-jts-idlj-5.2.12.Final.jar!/:5.2.12.Final (revision: f6563)]
	at com.arjuna.ats.jta.cdi.transactional.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:76) ~[narayana-jts-idlj-5.2.12.Final.jar!/:5.2.12.Final (revision: f6563)]
	at com.arjuna.ats.jta.cdi.transactional.TransactionalInterceptorRequiresNew.intercept(TransactionalInterceptorRequiresNew.java:47) ~[narayana-jts-idlj-5.2.12.Final.jar!/:5.2.12.Final (revision: f6563)]
	at sun.reflect.GeneratedMethodAccessor312.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:74) ~[weld-core-impl-2.3.2.Final.jar!/:2.3.2.Final]
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84) ~[weld-core-impl-2.3.2.Final.jar!/:2.3.2.Final]
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72) ~[weld-core-impl-2.3.2.Final.jar!/:2.3.2.Final]
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56) ~[weld-core-impl-2.3.2.Final.jar!/:2.3.2.Final]
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79) ~[weld-core-impl-2.3.2.Final.jar!/:2.3.2.Final]
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) ~[weld-core-impl-2.3.2.Final.jar!/:2.3.2.Final]
	at com.intel.podm.discovery.external.ServiceRemovalTask$Proxy$_$$_WeldSubclass.run(Unknown Source) ~[podm-discovery-2.1.3.4.0.jar:na]
	at com.intel.podm.common.synchronization.TaskCoordinatorImpl.lambda$scheduleWithFixedDelay$0(TaskCoordinatorImpl.java:81) ~[synchronization-2.1.3.4.0.jar:na]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_111]
	at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:235) ~[metrics-core-3.1.2.jar:3.1.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_111]
	at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:141) ~[javax.enterprise.concurrent-1.0.jar!/:na]
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$101(ManagedScheduledThreadPoolExecutor.java:383) ~[javax.enterprise.concurrent-1.0.jar!/:na]
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:532) ~[javax.enterprise.concurrent-1.0.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250) ~[javax.enterprise.concurrent-1.0.jar!/:na]

**Comment by tbykowsk** [comment]
Hi @rwleea, 

ServiceRemovalTask deletes services from PODM model if they stop responding. This task is scheduled at PODM initialization and should not be cancelled when an exception is thrown, but it takes place. PODM needs to be restarted in order to initialize ServiceRemovalTask again.

This issue have been addressed in [v2.2](https://github.com/intel/intelRSD/blob/Updated-sources-to-v2.2/PODM/SW/pod-manager/podm-discovery/src/main/java/com/intel/podm/discovery/external/ServiceRemovalTask.java), currently the task continues to run when an exception occurs.

It is not possible to determine what generated the `concurrent access timeout on DiscoveryScheduler` from your error message, which caused ServiceRemovalTask to stop.

**Comment by rwleea** [comment]
Hi @tbykowsk 

it seems  discoveryScheduler.cancel would execute over 5 seconds, Do you know what is the possible reason cause this method execute over 5 seconds?  ( I think I will increase timeout value)

**Comment by tbykowsk** [comment]
DiscoveryScheduler is annotated with `@javax.ejb.Singleton`, which implies that all of its public methods are [synchronized](https://docs.oracle.com/javaee/6/api/javax/ejb/Lock.html):
- scheduleServiceDiscoveryWithEventServiceSubscription()
- cancel()
- enqueueDiscovery()


When `cancel()` method signals that it cannot obtain a lock, this means another method is being executed and is holding the lock. Most likely `scheduleServiceDiscoveryWithEventServiceSubscription()` method - responsible for synchronized communication with services - is the blocking one.

**Comment by rwleea** [comment]
Hi @tbykowsk,
 
Thanks for your explanation.

I will think how to decrease the possibility of access timeout.
