### ISSUE TITLE
PODM 2.3 Service replied with HTTP{status=401, entity=null, location=null}

### ISSUE THREAD

**Issue by yiwong** [intel/intelRSD#85]
Dear Intel 
i meet the issuse(10.3.0.2 is psme ip,10.3.0.1 is podm ip):
2018-08-07 16:56:27,422 [EE-ManagedScheduledExecutorService-EventsExecutor-Thread-1] ERROR c.i.p.d.e.e.EventSubscriptionTask - Error while subscribing to event service for 89db5f2a-8fb0-11e8-8f58-9fe51e69a0e7 @ https://10.3.0.2:8443/redfish/v1
com.intel.podm.client.WebClientRequestException: Error while getting resource https://10.3.0.2:8443/redfish/v1/EventService from the external service
	at com.intel.podm.client.WebClientBasedOnRedfishClient.get(WebClientBasedOnRedfishClient.java:68) ~[podm-external-services-0.99.jar:na]
	at com.intel.podm.client.WebClientWithRetrying.lambda$get$0(WebClientWithRetrying.java:46) ~[podm-external-services-0.99.jar:na]
	at com.intel.podm.client.RetryInvoker.retry(RetryInvoker.java:45) ~[podm-external-services-0.99.jar:na]
	at com.intel.podm.client.WebClientWithRetrying.get(WebClientWithRetrying.java:46) ~[podm-external-services-0.99.jar:na]
	at com.intel.podm.client.events.EventSubscriptionManager.getEventService(EventSubscriptionManager.java:89) ~[podm-external-services-0.99.jar:na]
	at com.intel.podm.client.events.EventSubscriptionManager.fetchPodmSubscription(EventSubscriptionManager.java:77) ~[podm-external-services-0.99.jar:na]
	at com.intel.podm.discovery.external.event.EventSubscriptionTask.run(EventSubscriptionTask.java:65) ~[podm-discovery-0.99.jar:na]
	at com.codahale.metrics.InstrumentedScheduledExecutorService$InstrumentedRunnable.run(InstrumentedScheduledExecutorService.java:235) [metrics-core-3.1.2.jar:3.1.2]
	at org.jboss.as.ee.concurrent.ControlPointUtils$ControlledScheduledRunnable.run(ControlPointUtils.java:158) [wildfly-ee-12.0.0.Final.jar!/:12.0.0.Final]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_171]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_171]
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.access$201(ManagedScheduledThreadPoolExecutor.java:383) [javax.enterprise.concurrent-1.0.jar!/:na]
	at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$ManagedScheduledFutureTask.run(ManagedScheduledThreadPoolExecutor.java:534) [javax.enterprise.concurrent-1.0.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:250) [javax.enterprise.concurrent-1.0.jar!/:na]
	at org.jboss.as.ee.concurrent.service.ElytronManagedThreadFactory$ElytronManagedThread.run(ElytronManagedThreadFactory.java:78) [wildfly-ee-12.0.0.Final.jar!/:12.0.0.Final]
Caused by: com.intel.podm.client.redfish.response.RedfishClientException: Service replied with HTTP{status=401, entity=null, location=null}
	at com.intel.podm.client.redfish.response.RedfishResponseFactory.redfishResponseFromHttpResponse(RedfishResponseFactory.java:43) ~[podm-external-services-0.99.jar:na]
	at com.intel.podm.client.redfish.RedfishClient.get(RedfishClient.java:54) ~[podm-external-services-0.99.jar:na]
	at com.intel.podm.client.WebClientBasedOnRedfishClient.get(WebClientBasedOnRedfishClient.java:62) ~[podm-external-services-0.99.jar:na]
	... 17 common frames omitted

root@host004:/etc/network/interfaces.d# netstat 
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 localhost:42768         localhost:postgresql    ESTABLISHED
tcp        0      0 host004:ssh             192.168.202.155:50497   ESTABLISHED
tcp        0      0 host004:ssh             192.168.202.155:49648   ESTABLISHED
tcp        0      0 localhost:postgresql    localhost:42766         ESTABLISHED
tcp        0      0 10.3.0.1:56908          10.3.0.2:8443           TIME_WAIT
the detail error message are in the following log file,
[console.log](https://github.com/intel/intelRSD/files/2265810/console.log)
[server.log](https://github.com/intel/intelRSD/files/2265811/server.log)

Could you help ? thank you

**Comment by RobertCMa** [comment]
Hi @yiwong,

 From the log, it can see the port 8443 return 401 status. you can take use of curl or wget  to check if this psme (https://10.3.0.2:8443/redfish/v1) can respond properly at port 8443 first. 

2018-08-07 14:19:10,072 SEVERE [com.intel.podm.services.detection.ssdp.protocol.RetrieveRedfishServiceDescription] (EE-ManagedExecutorService-SSDPExecutor-Thread-14) Unable to retrieve Rack Scale service root for: https://10.3.0.2:8443/redfish/v1: com.intel.podm.discovery.external.UnrecognizedServiceTypeException: Unable to retrieve Rack Scale service root for: https://10.3.0.2:8443/redfish/v1

**Comment by yiwong** [comment]
Hi @RobertCMa,

root@host004:/etc/network/interfaces.d# curl https://10.3.0.2:8443/redfish/v1/ --insecure --user admin:admin
{"@odata.context":"/redfish/v1/$metadata#ServiceRoot.ServiceRoot","@odata.id":"/redfish/v1","@odata.type":"#ServiceRoot.v1_1_1.ServiceRoot","Id":"RootService","Name":"PSME Service Root","Description":"Service Root description","RedfishVersion":"1.1.0","UUID":"89db5f2a-8fb0-11e8-8f58-9fe51e69a0e7","EventService":{"@odata.id":"/redfish/v1/EventService"},"UpdateService":{"@odata.id":"/redfish/v1/UpdateService"},"Tasks":{"@odata.id":"/redfish/v1/TaskService"},"Registries":{"@odata.id":"/redfish/v1/Registries"},"Chassis":{"@odata.id":"/redfish/v1/Chassis"},"Systems":{"@odata.id":"/redfish/v1/Systems"},"Managers":{"@odata.id":"/redfish/v1/Managers"},"Fabrics":{"@odata.id":"/redfish/v1/Fabrics"},"TelemetryService":{"@odata.id":"/redfish/v1/TelemetryService"},"StorageServices":{"@odata.id":"/redfish/v1/StorageServices"},"Oem":{"Intel_RackScale":{"@odata.type":"#Intel.Oem.ServiceRoot","ApiVersion":"2.2.0","EthernetSwitches":{"@odata.id":"/redfish/v1/EthernetSwitches"}}},"Links":{}}

**Comment by RobertCMa** [comment]
Hi @yiwong 

From your curl, it does not use certification to communicate with PSME. Wonder if the certification is configured in PODM as it returns 401 Unauthorized Error. 

Please check the certification first and take use of "pod-manager-healthcheck" to generate the whole package of log.

**Comment by yiwong** [comment]
Hi @RobertCMa,

Certification has been plagued for a long time.

[pod_manager_health_check_2018-08-08-17-32-44-170.tar.gz](https://github.com/intel/intelRSD/files/2269723/pod_manager_health_check_2018-08-08-17-32-44-170.tar.gz)

Could you help ? thank you

**Comment by RobertCMa** [comment]
From the log, both services of postgresql and wildfly are not working properly. It's suggested to clarify the wildfly operation status first.

2018-08-08 09:39:59,509 ERROR [org.jboss.as.ee] (EE-ManagedScheduledExecutorService-TasksExecutor-Thread-1) WFLYEE0110: Failed to run scheduled task: java.lang.IllegalStateException: WFLYEE0111: Cannot run scheduled task 

2018-08-08 17:00:13,537 ERROR [org.jboss.as.ejb3.invocation] (EE-ManagedScheduledExecutorService-TasksExecutor-Thread-3) WFLYEJB0034: EJB Invocation failed on component EntityGraphMapper for method public void com.intel.podm.discovery.external.EntityGraphMapper.map(com.intel.podm.discovery.external.restgraph.RestGraph): javax.ejb.EJBTransactionRolledbackException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet

**Comment by yiwong** [comment]
the postgresql service error is Executing curl(curl -d '{"jsonrpc": "2.0", "method": "getComponents", "params": {"component" : ""}, "id":1}' localhost:7777 )  causes

**Comment by RobertCMa** [comment]
Hi @yiwong ,

Is the issue of wildfly resolved and does it help PODM work properly? Will like to clarify the current situation. Thanks.

**Comment by RobertCMa** [comment]
Hi @yiwong ,

Since there is no activities for a while, will conclude this issue here. New issues can be raised for the investigation. Thanks.
