### ISSUE TITLE
Question about How to find Intel PODM database source code

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#96]
Dear Intel -
the question is related to -
Intel PODM 2.3 connect PSME Compute Agent Simulator but PSQLException: ERROR: operator does not exist #93,

Q 1 -
I got PODM error message -
Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: text ~~ bytea
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 1291
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284) ~[na:na]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003) ~[na:na]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200) ~[na:na]

but I can't find the file - QueryExecutorImpl.java,
Could you help ? thanks.

Q 2 -
Could you have information about How to find PODM database source code ? 
thank you
House

**Comment by RobertCMa** [comment]
Hi @housemic,

The file and source are from open source of postgresql. You can check on the postgresql forum for more detail.
